### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by larrymandes** [nevmensik52/Indigo_Park-MAPPINGS#1]
please make a instruction I want to get all the media out of the files

**Comment by nevmensikD** [comment]
Follow these steps
1.Open Fmodel and go to settings
![image](https://github.com/nevmensikD/Indigo_Park-MAPPINGS/assets/166862773/19a04368-39ee-49be-83d4-6b2d615a0a94)
2.In settings find Mapping File Path
![image](https://github.com/nevmensikD/Indigo_Park-MAPPINGS/assets/166862773/b333f124-0191-41f5-893f-56a889d8fab1)
3. And use the path to Indigo_Park-MAPPINGS
